2021-11-16 11:57:48,099 INFO    MainThread:8096 [wandb_setup.py:_flush():71] setting env: {}
2021-11-16 11:57:48,099 INFO    MainThread:8096 [wandb_setup.py:_flush():71] setting login settings: {}
2021-11-16 11:57:48,099 INFO    MainThread:8096 [wandb_init.py:_log_setup():357] Logging user logs to c:\Users\ruben\VDoomLearning\src\wandb\run-20211116_115748-38p5m4dp\logs\debug.log
2021-11-16 11:57:48,100 INFO    MainThread:8096 [wandb_init.py:_log_setup():358] Logging internal logs to c:\Users\ruben\VDoomLearning\src\wandb\run-20211116_115748-38p5m4dp\logs\debug-internal.log
2021-11-16 11:57:48,100 INFO    MainThread:8096 [wandb_init.py:_jupyter_setup():307] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x0000021B2115D2E8>
2021-11-16 11:57:48,101 INFO    MainThread:8096 [wandb_init.py:init():390] calling init triggers
2021-11-16 11:57:48,101 INFO    MainThread:8096 [wandb_init.py:init():397] wandb.init called with sweep_config: {}
config: {}
2021-11-16 11:57:48,101 INFO    MainThread:8096 [wandb_init.py:init():435] starting backend
2021-11-16 11:57:48,101 INFO    MainThread:8096 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn, using: spawn
2021-11-16 11:57:48,108 INFO    MainThread:8096 [backend.py:ensure_launched():199] starting backend process...
2021-11-16 11:57:48,243 INFO    MainThread:8096 [backend.py:ensure_launched():205] started backend process with pid: 10488
2021-11-16 11:57:48,243 INFO    MainThread:8096 [wandb_init.py:init():444] backend started and connected
2021-11-16 11:57:48,324 INFO    MainThread:8096 [wandb_run.py:_label_probe_notebook():866] probe notebook
2021-11-16 11:57:48,326 INFO    MainThread:8096 [wandb_run.py:_label_probe_notebook():876] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2021-11-16 11:57:48,327 INFO    MainThread:8096 [wandb_init.py:init():503] updated telemetry
2021-11-16 11:57:48,415 INFO    MainThread:8096 [wandb_init.py:init():533] communicating current version
2021-11-16 11:57:53,418 INFO    MainThread:8096 [wandb_init.py:init():548] communicating run to backend with 30 second timeout
2021-11-16 11:58:23,427 INFO    MainThread:8096 [interface_queue.py:_communicate_run():336] couldn't get run from backend
2021-11-16 11:58:23,427 ERROR   MainThread:8096 [wandb_init.py:init():553] backend process timed out
2021-11-16 11:58:23,427 ERROR   MainThread:8096 [wandb_init.py:init():562] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2021-11-16 11:58:23,456 ERROR   MainThread:8096 [wandb_init.py:init():897] error
Traceback (most recent call last):
  File "C:\Users\ruben\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\wandb_init.py", line 870, in init
    run = wi.init()
  File "C:\Users\ruben\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\wandb_init.py", line 566, in init
    backend.cleanup()
  File "C:\Users\ruben\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\backend\backend.py", line 228, in cleanup
    self.interface.join()
  File "C:\Users\ruben\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 481, in join
    super(InterfaceQueue, self).join()
  File "C:\Users\ruben\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\interface\interface.py", line 591, in join
    self._communicate_shutdown()
  File "C:\Users\ruben\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 478, in _communicate_shutdown
    _ = self._communicate(record)
  File "C:\Users\ruben\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 232, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "C:\Users\ruben\AppData\Local\Programs\Python\Python36\lib\site-packages\wandb\sdk\interface\interface_queue.py", line 237, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
